image: maven:3-jdk-8
stages:
  - build test
  - create artifacts
build test:
  stage: build test
  script:
    - "mvn test"
  artifacts:
    when: always
    paths:
      - target/surefire-reports/TEST-*.xml
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
create artifacts:
  stage: create artifacts
  script:
    - "mvn test site"
  artifacts:
    when: always
    paths:
      - target/surefire-reports/TEST-*.xml
      - target/default-cucumber-reports/index.html
      - target/default-cucumber-reports/formatter.js
      - target/default-cucumber-reports/jquery-1.8.2.min.js
      - target/default-cucumber-reports/report.js
      - target/default-cucumber-reports/style.css
      - target/cucumber-html-reports/css/bootstrap.min.css
      - target/cucumber-html-reports/css/cucumber.css
      - target/cucumber-html-reports/css/font-awesome.min.css
      - target/cucumber-html-reports/fonts/FontAwesome.otf
      - target/cucumber-html-reports/fonts/fontawesome-webfont.eot
      - target/cucumber-html-reports/fonts/fontawesome-webfont.svg
      - target/cucumber-html-reports/fonts/fontawesome-webfont.ttf
      - target/cucumber-html-reports/fonts/fontawesome-webfont.woff
      - target/cucumber-html-reports/fonts/fontawesome-webfont.woff2
      - target/cucumber-html-reports/fonts/glyphicons-halflings-regular.eot
      - target/cucumber-html-reports/fonts/glyphicons-halflings-regular.svg
      - target/cucumber-html-reports/fonts/glyphicons-halflings-regular.ttf
      - target/cucumber-html-reports/fonts/glyphicons-halflings-regular.woff
      - target/cucumber-html-reports/fonts/glyphicons-halflings-regular.woff2
      - target/cucumber-html-reports/images/favicon.png
      - target/cucumber-html-reports/js/Chart.min.js
      - target/cucumber-html-reports/js/jquery.min.js
      - target/cucumber-html-reports/js/jquery.tablesorter.min.js
      - target/cucumber-html-reports/js/moment.min.js
      - target/cucumber-html-reports/js/bootstrap.min.js
      - target/cucumber-html-reports/overview-failures.html
      - target/cucumber-html-reports/overview-features.html
      - target/cucumber-html-reports/overview-steps.html
      - target/cucumber-html-reports/overview-tags.html
      - target/cucumber-html-reports/report-feature_1062200104.html
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/default-cucumber-reports/index.html
        - target/default-cucumber-reports/formatter.js
        - target/default-cucumber-reports/jquery-1.8.2.min.js
        - target/default-cucumber-reports/report.js
        - target/default-cucumber-reports/style.css
        - target/cucumber-html-reports/css/bootstrap.min.css
        - target/cucumber-html-reports/css/cucumber.css
        - target/cucumber-html-reports/css/font-awesome.min.css
        - target/cucumber-html-reports/fonts/FontAwesome.otf
        - target/cucumber-html-reports/fonts/fontawesome-webfont.eot
        - target/cucumber-html-reports/fonts/fontawesome-webfont.svg
        - target/cucumber-html-reports/fonts/fontawesome-webfont.ttf
        - target/cucumber-html-reports/fonts/fontawesome-webfont.woff
        - target/cucumber-html-reports/fonts/fontawesome-webfont.woff2
        - target/cucumber-html-reports/fonts/glyphicons-halflings-regular.eot
        - target/cucumber-html-reports/fonts/glyphicons-halflings-regular.svg
        - target/cucumber-html-reports/fonts/glyphicons-halflings-regular.ttf
        - target/cucumber-html-reports/fonts/glyphicons-halflings-regular.woff
        - target/cucumber-html-reports/fonts/glyphicons-halflings-regular.woff2
        - target/cucumber-html-reports/images/favicon.png
        - target/cucumber-html-reports/js/Chart.min.js
        - target/cucumber-html-reports/js/jquery.min.js
        - target/cucumber-html-reports/js/jquery.tablesorter.min.js
        - target/cucumber-html-reports/js/moment.min.js
        - target/cucumber-html-reports/js/bootstrap.min.js
        - target/cucumber-html-reports/overview-failures.html
        - target/cucumber-html-reports/overview-features.html
        - target/cucumber-html-reports/overview-steps.html
        - target/cucumber-html-reports/overview-tags.html
        - target/cucumber-html-reports/report-feature_1062200104.html