image: maven:3-jdk-8
stages:
  - build test
  - create artifacts
build test:
  stage: build test
  script:
    - "mvn test"
  artifacts:
    when: always
    paths:
      - target/surefire-reports/TEST-*.xml
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
create artifacts:
  stage: create artifacts
  script:
    - "mvn test site"
  artifacts:
    when: always
    paths:
      - target/surefire-reports/TEST-*.xml
      - target/default-cucumber-reports/index.html
      - target/default-cucumber-reports/formatter.js
      - target/default-cucumber-reports/jquery-1.8.2.min.js
      - target/default-cucumber-reports/report.js
      - target/default-cucumber-reports/style.css
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/default-cucumber-reports/index.html
        - target/default-cucumber-reports/formatter.js
        - target/default-cucumber-reports/jquery-1.8.2.min.js
        - target/default-cucumber-reports/report.js
        - target/default-cucumber-reports/style.css