image: maven:3-jdk-8
test:
  stage: test
  script:
    - "mvn verify"
  artifacts:
    when: always
    paths:
      - target/surefire-reports/TEST-*.xml
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml